# Generated by Django 2.2.4 on 2020-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200105_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
