# Generated by Django 2.2.4 on 2020-01-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
